### ISSUE TITLE
typings 1.0 release breaks angular2.step_00

### ISSUE THREAD

**Issue by bwillacker** [Urigo/angular-meteor-docs#108]
Hello -

Looks like the typings has been updated and the api has changed with 1.0. On step 0, the angular2-meteor tutorial calls for:

  $ npm install typings -g
  $ typings init
  $ typings install es6-promise --save
  $ typings install es6-shim --ambient --save
  $ typings install registry:env/meteor --ambient

It looks like `--ambient` has changed to `--global` and installing from DefinitelyTyped requires that you explicitly to call it out as the source via `~dt`. Here's what I ended up going with:

  $ npm install typings -g
  $ typings init
  $ typings install es6-promise --save
  $ typings install dt~es6-shim --global --save
  $ typings install registry:env/meteor --global

Side note: Is there a reason we don't save the meteor typings to typings.json?

If these changes look good, let me know and I'll create a PR.

Thank you!

**Comment by Urigo** [comment]
someone just PRed it and I've deployed it, can you clean cache and look and the site and see if it's ok now?

**Comment by bwillacker** [comment]
Thanks for the quick response @Urigo. I'll test out the updated syntax later this afternoon and confirm resolved.

**Comment by bwillacker** [comment]
Ran through commands again. Performed copy/paste to confirm. Worked great, thanks @Urigo!
