### ISSUE TITLE
Step 4 seems overcomplicated 

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#109]
I'm new to Angular 2 and Meteor, but to me it looks like the `#f="ngForm" (submit)="addParty(f.value)"` could be simply `(submit)="addParty()"`, since we are going to access the `this.partiesForm` in the event handler anyway.
I mean:

```
  addParty(party) {
    if (this.partiesForm.valid) {
      Parties.insert({
        name: party.name,
        description: party.description,
        location: party.location
      });

      (<Control>this.partiesForm.controls['name']).updateValue('');
      (<Control>this.partiesForm.controls['description']).updateValue('');
      (<Control>this.partiesForm.controls['location']).updateValue('');
    }
  }
```

could be replaced with:

```
  addParty() {
    if (this.partiesForm.valid) {
      Parties.insert(this.partiesForm.value);

      (<Control>this.partiesForm.controls['name']).updateValue('');
      (<Control>this.partiesForm.controls['description']).updateValue('');
      (<Control>this.partiesForm.controls['location']).updateValue('');
    }
  }
```

I would also suggest to change "TypeScript doesn't know that controls properties are of Control type" to "TypeScript thinks that controls properties are of a more general AbstractControl type which requires us to downcast to Control type", as the original version made me needlessly me worried about the abilities of TypeScript.

**Comment by kamilkisiela** [comment]
@qbolec @Urigo This has changed in the newest tutorial

**Comment by Urigo** [comment]
closing, please open a new issue if the problem still happens
