### ISSUE TITLE
Step 7's Type Declaration Files chapter is outdated

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#111]
The names of files mentioned in chapter Type Declaration Files are not the ones I can see in typings.
After carefully following previous Steps, using latest `typings` and `angular2-meteor`, I can see the following content in the typings folder:

```
./index.d.ts
./globals
./globals/es6-shim
./globals/es6-shim/index.d.ts
./globals/es6-shim/typings.json
./globals/meteor
./globals/meteor/index.d.ts
./globals/meteor/typings.json
./modules
./modules/es6-promise
./modules/es6-promise/index.d.ts
./modules/es6-promise/typings.json
```

while the chapter mentions things like meteor.d.ts, angular2.d.ts and angular2-meteor.d.ts, none of which I can find here.
I'm almost sure that globals/meteor/index.d.ts plays the same role as meteor.d.ts did, but the angular2.d.ts and angular2-meteor.d.ts are probably hidden somewhere in the ./node_modules, I guess. Probably ./node_modules/angular2-meteor/typings/main.d.ts is one of them?

I'm not proposing changes to this chapter as a pull request, because, honestly, I have no clue how it really works :(

**Comment by kamilkisiela** [comment]
@qbolec @Urigo Tutorial has changed, we're using [`angular2-boilerplate`](https://github.com/meteor/meteor/pull/7363)

**Comment by Urigo** [comment]
closing, please open a new issue if the problem still happens
