### ISSUE TITLE
Steps 7's TypeScript Configuration and IDEs seems outdated

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#112]
The section about 'TypeScript Configuration and IDEs' talks about tsconfig.json containing only the 'files' property, but in the Step 0, I was instructed to put : 

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "module": "commonjs",
    "target": "es5",
    "isolatedModules": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "removeComments": false,
    "noImplicitAny": false,
    "sourceMap": true
  },
  "filesGlob": [
    "client/**/*.ts",
    "server/**/*.ts",
    "typings/**/*.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

in it. Something is wrong here.

**Comment by kamilkisiela** [comment]
@qbolec With the new version we no longer use `filesGlob`, only `exclude`.

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
