### ISSUE TITLE
Step 8's "Routing Permissions" ignores past changes

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#115]
There is a paragraph in the "Routing Permissions" section:

> This can be easily done again with help of "angular2-meteor-accounts-ui" package that has a simple RequireUser annotation. Just place it above PartyDetails and you will see if a user is not logged-in to the system, that user won't be able to access the route.

which seems very odd, because I already have added the RequireUser annotation, as I was kindly asked in the "RequireUser" section.
What's even more puzzling to me, is this does not sound like a perfect solution, which was promissed in a previous paragraph:

>  An ideal way to implement this would be to restrict redirecting to the party details page when someone clicks on a party link. In this case, we don't need to check access manually in the party details component itself because the route request is denied early on.

Based on the paragraph above, I was expecting a change to be applied somewhere near the RouteConfig in app.ts, and not in the PartyDetails.

**Comment by kamilkisiela** [comment]
@qbolec `RequireUser` has been deprecated. To be familiar with recent changes, please follow the new tutorial :)

@Urigo

**Comment by Urigo** [comment]
closing, please open a new issue if the problem still happens
