### ISSUE TITLE
Step 8's InjectUser requires a parameter

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#116]
The tutorial suggests to use `@InjectUser()` without params, but:

```
$ cat ./node_modules/angular2-meteor-accounts-ui/build/annotations.d.ts
export declare function InjectUser(propName: string): (cls: any) => any;
export declare const RequireUser: any;
```

which I believe is the reason for the warning:

```
client/imports/parties-form/parties-form.ts (13, 2): Supplied parameters do not match any signature of call target.
```

I think, that either the d.ts file should mark the parameter as optional, or the string "user" should be passed to InjectUser annotation in the tutorial code.

**Comment by kamilkisiela** [comment]
@qbolec @Urigo It no longer does. Tutorial has been updated :)

**Comment by Urigo** [comment]
closing, please open a new issue if the problem still happens
