### ISSUE TITLE
Step 8's Routing Permissions code example seems outdated

### ISSUE THREAD

**Issue by qbolec** [Urigo/angular-meteor-docs#117]
The code example presented in "Routing Permissions" section : 

```
import {CanActivate, ComponentInstruction} from '@angular/router-deprecated';

function checkPermissions(instruction: ComponentInstruction) {
  var partyId = instruction.params['partyId'];
  var party = Parties.findOne(partyId);
  return (party && party.owner == Meteor.userId());
}

Component({
  selector: 'party-details'
})
@View({
    templateUrl: 'client/imports/party-details/party-details.html',
    directives: [RouterLink]
})
@CanActivate(checkPermissions)
export class PartyDetails {
  ...
}
```

seems strange:
- it's not clear from previous parts of the tutorial what is the `@View` annotation, and where to import it from
- from my previous investigation it seems problematic that there is no slash before "client" in the templateUrl
- it seems strange that there is no `@` before the word "Component"
- the PartyDetails should inherit from MeteorComponent at this point of tutorial

**Comment by qbolec** [comment]
It also seems that this particular implementation of `checkPermissions` does not work right when I press F5, pressumably because the `Parties.findOne(party)` returns `undefined` before the collection is ready, and thus the return value is falsy.

**Comment by kamilkisiela** [comment]
@qbolec @Urigo Tutorial has been updated

**Comment by Urigo** [comment]
closing, please open a new issue if the problem still happens
