### ISSUE TITLE
"CSS, LESS and Bootstrap" is a dead link

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#12]
http://www.angular-meteor.com/tutorials/socially/angular2/css-less-and-bootstrap is a dead link.

Try to go here: http://www.angular-meteor.com/tutorials/socially/angular2/google-maps and click `17. CSS, LESS and Bootstrap` or `Next`, the content showing is actually not the content from `17. CSS, LESS and Bootstrap`.

**Comment by Urigo** [comment]
thanks! fixes by @dotansimha and deployed now with all of your awesome PRs!

**Comment by hongbo-miao** [comment]
You are welcome!
