### ISSUE TITLE
Remove warning in tutorial step 5.2

### ISSUE THREAD

**Issue by Sauermann** [Urigo/angular-meteor-docs#121]
In step 5,2 of http://www.angular-meteor.com/tutorials/socially/angular2/routing-and-multiple-views

```
parties: Mongo.Cursor;
```

should be changed to

```
parties: Mongo.Cursor<Object>;
```

in order to remove the warning

```
client/imports/parties-list/parties-list.ts (13, 13): Generic type 'Cursor<T>' requires 1 type argument(s).
```

**Comment by kamilkisiela** [comment]
@Urigo done in the latest version of the tutorial

**Comment by Sauermann** [comment]
Thanks!
