### ISSUE TITLE
Step 3.3 has '=&gt;' written , instead of '=>'

### ISSUE THREAD

**Issue by ghost** [Urigo/angular-meteor-docs#123]
at:   **Meteor.startup(() **
and at: **parties.forEach((party)**

**Comment by betrin** [comment]
http://www.angular-meteor.com/tutorials/socially/angular1/adding-removing-objects-and-angular-event-handling. It's the same file, but the change will be good on this web page too, to avoid confusion
same issue in step  4.10

![image](https://cloud.githubusercontent.com/assets/10996124/15547137/70ab6cd2-229a-11e6-96fb-028dacaba831.png)

**Comment by betrin** [comment]
Also multiple cases on 
"4.22  Tests of PartyAdd"
and 
"4.23  Tests of PartyRemove"

**Comment by kamilkisiela** [comment]
meteor/tutorial-tools#13 should fix it
