### ISSUE TITLE
Step 0: Typings PATH

### ISSUE THREAD

**Issue by Sauermann** [Urigo/angular-meteor-docs#124]
On http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping
after installing typings ("npm install typings -g") the following commands fail, because typings is not installed into a directory that is mentioned in the PATH variable.

As a workaround, I included

```
C:\Users\<USERNAME>\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\bin
```

on Windows and

```
/home/<USERNAME>/.meteor/packages/meteor-tool/.1.3.2_4.10vjklo++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/bin
```

on Linux to the PATH variable.

**Comment by Sauermann** [comment]
I found another workaround for this issue: install node.js.
Perhaps somewhere in the tutorial it should be mentioned that node.js should be installed?

**Comment by Urigo** [comment]
@Sauermann do you mind creating a PR for the tutorial to make this more clear?

**Comment by Sauermann** [comment]
@Urigo Actually I do mind, since I have no idea which of the two mentionend workarounds is the recommended solution.

**Comment by Urigo** [comment]
@Sauermann installing node
