### ISSUE TITLE
Step 14.13 not working for me 

### ISSUE THREAD

**Issue by Rahman-S-M** [Urigo/angular-meteor-docs#125]
the line 
let type = args[0]; 
is not working for me. it is taking the first character ie., y,m and n from yes,maybe or no

Yes - {{party | rsvp:'yes'}}
        Maybe - {{party | rsvp:'maybe'}}
        No - {{party | rsvp:'no'}}

I replaced the line with 
let type = args; 
and it works fine.

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
