### ISSUE TITLE
The outcome following step 0 is different to the sample project around typings

### ISSUE THREAD

**Issue by sunshineo** [Urigo/angular-meteor-docs#134]
Following https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping the result of the content of "typings" folder is different to https://github.com/Urigo/meteor-angular2.0-socially/tree/master/typings
No browser folder, no browser.d.ts
Have a index.d.ts instead of main.d.ts
Have a globe and a modules folder instead of a main folder.

When run meteor, compile complains a lot about "Cannot find module" like this

```
client/imports/parties-form/parties-form.ts (2, 27): Cannot find module '@angular/core'.
client/imports/parties-form/parties-form.ts (3, 64): Cannot find module '@angular/common'.
client/imports/parties-form/parties-form.ts (6, 31): Cannot find module 'angular2-meteor'.
client/imports/parties-form/parties-form.ts (7, 28): Cannot find module 'angular2-meteor-accounts-ui'.
client/imports/parties-list/parties-list.ts (1, 29): Cannot find module '@angular/core'.
client/imports/parties-list/parties-list.ts (5, 29): Cannot find module '@angular/router-deprecated'.
client/imports/parties-list/parties-list.ts (6, 30): Cannot find module 'angular2-meteor-accounts-ui'.
client/imports/parties-list/parties-list.ts (7, 33): Cannot find module 'angular2-meteor'.
```

Can we update the tutorial to put the most up to date commands? Basically whatever command @Urigo did for https://github.com/Urigo/meteor-angular2.0-socially/commit/54506ac271beb90285497b122e6df2753660c3fe

Thank you very much!

**Comment by kamilkisiela** [comment]
@sunshineo you should run `meteor npm install`.

@Urigo This should be fixed with the boilerplate
