### ISSUE TITLE
Step 0.2 - Angular2 not installed when Running 'meteor npm install --save angular2-meteor @angular/platform-browser-dynamic'

### ISSUE THREAD

**Issue by ghost** [Urigo/angular-meteor-docs#135]
Should add dependency or add  'npm install angular2' to the guide

**Comment by sunshineo** [comment]
+1
Something is missing in that step.
The "meteor npm install --save angular2-meteor @angular/platform-browser-dynamic" gave a lot of warnings and when you reach the end, the page does not work.

**Comment by dotansimha** [comment]
@derosenyelen How to did install the NPM dependencies? using `npm install` or `meteor npm install`? 
And can you check the versions? (add `--version`) 

Thanks

**Comment by sunshineo** [comment]
Hi @dotansimha , I followed https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping word by word and when I reach the end of the page and start meteor, I got this
![am2](https://cloud.githubusercontent.com/assets/1072766/16597621/c5dc433c-42ae-11e6-8e48-d9e6f36cadcf.jpg)

**Comment by artmadeit** [comment]
yeah I have the same problem that all of you until I find the issue #315 from angular2-meteor 
https://github.com/Urigo/angular2-meteor/issues/315 , which resolves the problem

See the post to get in details...but probably all you have to do is what they said:

> After adding Angular2 and the dependencies from the tutorial at step 0.2, I just did:
> meteor npm install --save @angular/common@2.0.0-rc.1
> and so on for all of the peer dependencies, plus angular2-meteor-polyfills.

I recommend to use the latest versions of the modules...so instead of this
`meteor npm install --save @angular/common@2.0.0-rc.1`
use this:
`meteor npm install --save @angular/common@2.0.0-rc.4`

So your package.json gets like this

``` javascript
{
  {
  "name": "socially",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "@angular/common": "^2.0.0-rc.4",
    "@angular/compiler": "^2.0.0-rc.4",
    "@angular/core": "^2.0.0-rc.4",
    "@angular/platform-browser": "^2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.4",
    "angular2-meteor": "^0.5.6",
    "angular2-meteor-polyfills": "^0.1.1",
    "es6-shim": "^0.35.1",
    "meteor-node-stubs": "~0.2.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^5.0.0-beta.6",
    "zone.js": "^0.6.12"
  }
}
```

I hope this helps :)
I also expect that the tutorial and docs update this bug.
Good luck !!

**Comment by sunshineo** [comment]
Thanks @ArthurMauricioDelgadillo 
I installed a bunch of things and then it worked.
I'll compile a list.

**Comment by Urigo** [comment]
great!  thank you for updating

**Comment by sunshineo** [comment]
Here is the command you can use that for me run smoothly without any warnings and the page works.

```
meteor npm install --save meteor-node-stubs reflect-metadata @angular/core@^2.0.0-rc.2 angular2-meteor angular2-meteor-polyfills@^0.1.1 rxjs@5.0.0-beta.6 zone.js@^0.6.6 @angular/core@^2.0.0-rc.4 @angular/common@^2.0.0-rc.4 @angular/compiler@^2.0.0-rc.4 @angular/platform-browser@^2.0.0-rc.4 @angular/platform-browser-dynamic
```

**Comment by sunshineo** [comment]
I created a pull request https://github.com/Urigo/angular-meteor-docs/pull/177
To update the tutorial
