### ISSUE TITLE
On page reload the page is blank

### ISSUE THREAD

**Issue by simonv3** [Urigo/angular-meteor-docs#137]
When following the instructions in step 5, if you go to a direct URL and load the page it's blank.

This is probably because of the fact that the server doesn't recognize the routes.

Following this answer on SO fixes it, and is probably the simplest answer: http://stackoverflow.com/a/35052147/154392

Should this be in the tutorial? Did I miss something?

**Comment by kamilkisiela** [comment]
@simonv3 

This might be helpful
https://github.com/Urigo/meteor-angular2.0-socially/issues/90#issuecomment-223009500

**Comment by Urigo** [comment]
Fixed by @kamilkisiela and deployed
