### ISSUE TITLE
Step 1.14 step not working + solution

### ISSUE THREAD

**Issue by jdrzj** [Urigo/angular-meteor-docs#140]
Hi, I stucked at the step 1.14 of whatsapp meteor angular tutorial. None of messages apperead. I spend a couple of minutes to diff my project with tutorial's project on github(https://github.com/DAB0mB/angular-meteor-whatsapp). Looks like missing is mention about adding line `controller: 'ChatsCtrl as chats'` in client/scripts/lib/routes.js.
Hope I helped somebody with same issue.

**Comment by Urigo** [comment]
fixed and deployed.
Please open another issue if it's not working for you
