### ISSUE TITLE
Windows fails to read valid tsconfig.json (under Step 0 Bootstrapping)

### ISSUE THREAD

**Issue by alexreich** [Urigo/angular-meteor-docs#141]
On [this page](http://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping), meteor fails to run at step 0.8:

`=> Started proxy.
=> Started MongoDB.
Compiling main app HTML file: client/index.html
Compiling HTML template: client/app.html
=> Errors prevented startup:

   While processing files with barbatus:typescript (for target
   web.browser):
   packages/barbatus:typescript-compiler/typescript-compiler.js:186:13:
   Format of the tsconfig is invalid: SyntaxError: Unexpected token ?
   at TypeScriptCompiler.parseConfig
   (packages/barbatus:typescript-compiler/typescript-compiler.js:186:13)
   at TypeScriptCompiler.processConfig
   (packages/barbatus:typescript-compiler/typescript-compiler.js:161:30)
   at TypeScriptCompiler.processFilesForTarget
   (packages/barbatus:typescript-compiler/typescript-compiler.js:22:10)`

**Comment by jgg3** [comment]
I discovered the solution to this problem today.  Apparently, on Windows, if you use a text editor that creates a UTF-8 BOM (I was using VS 2015), the tsconfig parser cannot handle it.  I found mentions of this in other contexts across the web.  So I saved tsconfig.json as ANSI (from NotePad++), and it worked (but still has the "Cannot find module './app.html' message).

**Comment by kamilkisiela** [comment]
Can you please check it with the latest version of Socially 2.0 tutorial?

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
