### ISSUE TITLE
Problem with "Step 3 - 3-Way data binding" (solved?)

### ISSUE THREAD

**Issue by srokatonie** [Urigo/angular-meteor-docs#148]
After unzipping Step 3 the browser shows:

`imports/ui/components/socially/socially.html`

Instead of the list of the parties

![screen shot 2016-06-03 at 11 27 02](https://cloud.githubusercontent.com/assets/12460055/15776212/2df6ed54-297e-11e6-8098-a35dbe4a5ba9.png)

**Comment by srokatonie** [comment]
I think it's because in tutorial component template declaration is:

```
import template from './partiesList.html';

// ...

  PartyAdd,
  PartyRemove
]).component(name, {
  template,
  controllerAs: name,
  controller: PartiesList
})
```

I think https://www.meteor.com/tutorials/angular/creating-an-app is a bit more up to date with current version of Angular:

```
import templateUrl from './partiesList.html';

// ...

  PartyAdd,
  PartyRemove
]).component(name, {
  templateUrl,
  controller: PartiesList
})
```

**Comment by kamilkisiela** [comment]
@srokatonie It depends on what template package you're using.

a) `angular-templates` exports an absolute path of html file.
b) `urigo:static-templates` exports html file as a string.

``` js
// a)
import templateUrl from './partiesList.html';
console.log(templateUrl); // client/.../partiesList.html
```

``` js
// b)
import template from './partiesList.html';
console.log(template); // <div>...</div>
```

**Comment by srokatonie** [comment]
@kamilkisiela Thanks for clarification.
