### ISSUE TITLE
13.14  Create PartyCreator component - Meteor.users returns only logged in user

### ISSUE THREAD

**Issue by srokatonie** [Urigo/angular-meteor-docs#155]
The following will always return "nobody" since Meteor.users contains only currently logged user.

```
// imports/ui/components/partyCreator/partyCreator.js
//...
return Meteor.users.findOne(owner) || 'nobody';
```

It works after you add `this.subscribe('users');`.

 Should that be in `partyCreator.js` or in parent component?

**Comment by DAB0mB** [comment]
@srokatonie I already fixed it https://github.com/Urigo/angular-meteor/issues/1447. @Urigo this can be closed.
