### ISSUE TITLE
constants.js:66 Uncaught TypeError: Cannot read property 'CheckOnce' of undefined

### ISSUE THREAD

**Issue by ramonprata** [Urigo/angular-meteor-docs#169]
I'm trying to run  a simple "hello world" angular2-meteor app, and I'm getting an 
error: constants.js:66 Uncaught TypeError: Cannot read property 'CheckOnce' of undefined
on the browser. Can anyone help me?!

**Comment by hongbo-miao** [comment]
Link to https://github.com/Urigo/angular2-meteor-auto-bootstrap/issues/20

**Comment by Urigo** [comment]
@ramonprata @Hongbo-Miao can you please provide a repository with a reproduction?

**Comment by Hongbo-Miao** [comment]
sure, I will provide one soon

**Comment by hongbo-miao** [comment]
@ramonprata 
Like @barbatus said, location of CheckOnce might have changed.

CheckOnce is from Angular2's ChangeDetectionStrategy.
So I solved it by updating 

```
"@angular/common": "2.0.0-rc.1",
"@angular/core": "2.0.0-rc.1",
"@angular/platform-browser": "2.0.0-rc.1",
"@angular/platform-browser-dynamic": "2.0.0-rc.1",
```

to

```
"@angular/common": "2.0.0-rc.4",
"@angular/core": "2.0.0-rc.4",
"@angular/platform-browser": "2.0.0-rc.4",
"@angular/platform-browser-dynamic": "2.0.0-rc.4",
```

**Comment by Urigo** [comment]
thanks @Hongbo-Miao !
