### ISSUE TITLE
<Control> is missing in the tutorial

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#18]
In the document `client/parties-form/parties-form.ts` of [source code](https://github.com/Urigo/meteor-angular2.0-socially/compare/step_03...step_04):

```
(<Control>this.partiesForm.controls['name']).updateValue('');
(<Control>this.partiesForm.controls['description']).updateValue('');
(<Control>this.partiesForm.controls['location']).updateValue('');
```

These are correct.

However, in the tutorial, Step [4.9  Add addParty method into the component](http://www.angular-meteor.com/tutorials/socially/angular2/adding-removing-objects-and-angular-event-handling), it shows:

```
(this.partiesForm.controls['name']).updateValue('');
(this.partiesForm.controls['description']).updateValue('');
(this.partiesForm.controls['location']).updateValue('');
```

`<Control>` is missing.

**Comment by dotansimha** [comment]
Duplicate https://github.com/Urigo/angular-meteor-docs/issues/23
