### ISSUE TITLE
CollectionFS -> UploadFS

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#185]
All [these places](https://github.com/Urigo/angular-meteor-docs/search?utf8=%E2%9C%93&q=CollectionFS) including CollectionFS can be changed. Because the tutorial is not using CollectionFS at all.

**Comment by Urigo** [comment]
could you create a PR to solve it?

**Comment by hongbo-miao** [comment]
sure!

**Comment by hongbo-miao** [comment]
Oh, I remembered why I didn't do a PR before, because it has a lot of links. So I am afraid of breaking the links..

**Comment by Urigo** [comment]
you can try, it there is a bug, I can help you with it
