### ISSUE TITLE
Step 5.15 NgZone is necessary?

### ISSUE THREAD

**Issue by artmadeit** [Urigo/angular-meteor-docs#186]
Hi, the tutorial says:

> To apply any change of party to UI, we have to use NgZone.run() method. 

But I try to see if the UI change when I update the selected party (the party detail) on mongo terminal and  it changes without using NgZone.run().

So I have a party called Arthur...
![image](https://cloud.githubusercontent.com/assets/18428325/16941025/2399b578-4d53-11e6-9f30-dcb48ae89e8d.png)

And I update on mongo terminal to Diana party and both the detail and the list updates without using NgZone.run()
![image](https://cloud.githubusercontent.com/assets/18428325/16941039/41b06980-4d53-11e6-8687-0f8326a4fdbd.png)

Please send me your respond, best regards

**Comment by hongbo-miao** [comment]
Since Angular2-Meteor v0.5.6, `autorun` binds NgZone by default. The tutorial has not been updated to latest version.

**Comment by artmadeit** [comment]
The API docs was updated on  https://github.com/Urigo/angular-meteor-docs/pull/187
