### ISSUE TITLE
templateUrl should not be deleted

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#19]
For step [5.4 Clean up app.ts file](http://www.angular-meteor.com/tutorials/socially/angular2/routing-and-multiple-views), right now is

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
import {ROUTER_PROVIDERS, ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';

@Component({
  selector: 'app',
  directives: [ROUTER_DIRECTIVES]
})
class Socially {}

bootstrap(Socially, [ROUTER_PROVIDERS]);
```

However, `templateUrl: 'client/app.html',` should not be deleted in this "clean" step. Otherwise, it will show the error:

> EXCEPTION: Component 'Socially' must have either 'template' or 'templateUrl' set.

The correct one should be like below. 

**client/app.ts**

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2-meteor-auto-bootstrap';
import {ROUTER_PROVIDERS, ROUTER_DIRECTIVES, RouteConfig} from 'angular2/router';

@Component({
  selector: 'app',
  templateUrl: 'client/app.html',
  directives: [ROUTER_DIRECTIVES]
})
class Socially {}

bootstrap(Socially, [ROUTER_PROVIDERS]);
```

And delete all content in the **client/app.html** file in this step.

**Comment by Urigo** [comment]
I've deployed the fix.
@Hongbo-Miao can you please check if it's ok now?

**Comment by hongbo-miao** [comment]
Look nice!
