### ISSUE TITLE
Angular2-meteor tutorial

### ISSUE THREAD

**Issue by bfonacier** [Urigo/angular-meteor-docs#192]
Any clue anyone?  After going through the initial Meteor Setup, I was NOT able to run the meteor server due to the following errors:

bfonacier@bfonacier-VirtualBox:~/projects/socially$ meteor
[[[[[ ~/projects/socially ]]]]]               

=> Started proxy.  
=> Started MongoDB.  
=> Errors prevented startup:                  

   While determining active plugins:
   error: conflict: two packages included in the app (templating and
   angular2-compilers) are both trying to handle *.html

   While determining active plugins:
   error: conflict: two packages included in the app (templating and
   angular2-compilers) are both trying to handle *.html

=> Your application has errors. Waiting for file change.

**Comment by nebiljabari** [comment]
I think you forgot to remove Blaze. Meteor doesn't allow 2 templates renders
`$ meteor remove blaze-html-templates`

**Comment by hongbo-miao** [comment]
@bfonacier Richie765 met same issue and solved, check here https://github.com/Urigo/angular2-meteor/issues/317

**Comment by Urigo** [comment]
the tutorial was updated and deployed.
Please open another issue if it doesn't work for you
