### ISSUE TITLE
Step 8 - Missing setup OAuth login for Facebook & Twitter

### ISSUE THREAD

**Issue by Oya** [Urigo/angular-meteor-docs#195]
Missing setup OAuth login for Facebook & Twitter and angular2-meteor-accounts-ui support this?

**Comment by artmadeit** [comment]
As I mention on https://github.com/Urigo/meteor-angular2.0-socially/issues/113

> The package angular2-meteor-accounts-ui can't support accounts for facebook,twitter,google

I also hope that the tutorial show that..

**Comment by Urigo** [comment]
would community contribution to that
