### ISSUE TITLE
unclear description of WhatsApp 2 tutorial step 3.15

### ISSUE THREAD

**Issue by carstenbaumhoegger** [Urigo/angular-meteor-docs#227]
There's a note after step 3.15 that says

> NOTE: meteor-client-side will try to connect to localhost:3000 by default. To change it, simply set a global object named **meteor_runtime_config** with a property called DDP_DEFAULT_CONNECTION_URL and set whatever server url you'd like to connect to.

I tried to change the default port to `http://myip:port` by calling `export DDP_DEFAULT_CONNECTION_URL=http://myip:port` before doing `ionic serve` but meteor still seems to try to connect to `http://localhost:3000`

Would it be possible to give a more clear explanation what to to to make Meteor connect to the custom IP?

**Comment by dotansimha** [comment]
You need to set it as global variable in the JavaScript context, for example:

``` js
window.__meteor_runtime_config__= { DDP_DEFAULT_CONNECTION_URL: "..."};

import "meteor-client-side";
```

It's mentioned in the meteor-client-side pcakage docs (https://github.com/idanwe/meteor-client-side)
