### ISSUE TITLE
<Party> is missing

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#23]
In step **7.3 Define parties collection with Party type**, http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure

Right now is
`export var Parties = new Mongo.Collection('parties');`

it should be
`export var Parties = new Mongo.Collection<Party>('parties');`

**Comment by hongbo-miao** [comment]
Similar in step **7.4  Correct parties cursor to be of the exact type**

Should be `parties: Mongo.Cursor<Party>;`

**Comment by hongbo-miao** [comment]
Seems like all things like `<Something>` are missing in the tutorial, while the source codes are correct.
It means those code boxes does show codes completely.

**Comment by dotansimha** [comment]
Thats an issue in https://github.com/meteor/tutorial-tools/issues/8 , I think I will fix it tomorrow and PR

**Comment by dotansimha** [comment]
Closed in https://github.com/Urigo/angular-meteor-docs/pull/46
