### ISSUE TITLE
Whatsapp Tutorial broken step 3 

### ISSUE THREAD

**Issue by robertclarkson** [Urigo/angular-meteor-docs#248]
{{> DiffBox tutorialName="whatsapp-meteor-tutorial" step="3.24"}}

This diff is missing: "type: String,"

should be

```
check(message, {
      text: String,
      type: String,
      chatId: String
    });
```

**Comment by DAB0mB** [comment]
@robertclarkson Already fixed, see https://www.angular-meteor.com/tutorials/whatsapp/meteor/methods. @Urigo this can be closed.
