### ISSUE TITLE
Angular2 Meteor Socially Tutorial step 0 broken

### ISSUE THREAD

**Issue by Nauzer** [Urigo/angular-meteor-docs#250]
After installing 'angular2-meteor-auto-bootstrap' myself I can run the app of 
https://www.angular-meteor.com/tutorials/socially/angular2/bootstrapping

However in the browser console I get the following error:
`core.umd.js:403 Uncaught reflect-metadata shim is required when using class decorators`

After adding the following to app.component.ts:

`import 'reflect-metadata';`

The console error changes to:

`index.umd.js:21 Uncaught TypeError: Cannot read property 'current' of undefined`

---

running meteor npm install give the following errors:

```
angular2-meteor-base@ /Users/Nauzer/Documents/DevShed/socially
├── UNMET PEER DEPENDENCY angular2-meteor@0.7.0-beta.2
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

npm WARN angular2-meteor-auto-bootstrap@0.6.0 requires a peer of angular2-meteor@^0.6.0 but none was installed.
npm WARN meteor-rxjs@0.1.0 requires a peer of rxjs@5.0.0-beta.11 but none was installed.
```

**Comment by Nauzer** [comment]
I just installed the zip with step 1 with the working project up to that step and that works - it contains angular2 rc4 however. Something is breaking with step 0 with the latest 2.0.0 release version of angular and it's dependencies (see above).

**Comment by Urigo** [comment]
Hi everyone and sorry for the late response.
We were hard at work for updating to the latest Angular 2.0 stable.
Please try the new `angular2-meteor@0.7.0`, `angular2-compilers@0.6.3` and the latest Angular 2.0.

We've update the Socially 2.0 tutorial and the Blaze to Angular 2 migration tutorial for reference - https://www.angular-meteor.com/migration/angular2/intro

Sorry for the long wait, it was very hard to keep up with Angular 2 releases in latest months.

If you find issues, please open new ones on the Github repo.
