### ISSUE TITLE
Socially 2 tutorial broken step 3

### ISSUE THREAD

**Issue by artmadeit** [Urigo/angular-meteor-docs#253]
Get the error:
![image](https://cloud.githubusercontent.com/assets/18428325/19089486/1aa60fbe-8a40-11e6-8e5f-3d10d7506516.png)

The problem is on the [angular2.step_02.md](https://github.com/Urigo/angular-meteor-docs/blob/master/client/content/tutorials/socially/angular2/tutorials.socially.angular2.step_02.md)
which uses: `{{> DiffBox tutorialName="meteor-angular2-socially" step="2.3"}}`. Also if we are using now Observable, this [step](https://github.com/Urigo/meteor-angular2.0-socially/commit/6a9af316a3c5588ecae4cb89befb8f0d1ff3277b) will need to change to use the async pipe

**Comment by Urigo** [comment]
ok we are on it, thanks

**Comment by artmadeit** [comment]
Fixed by https://github.com/Urigo/angular-meteor-docs/pull/254/files
