### ISSUE TITLE
Consider running: meteor npm install --save meteor-node-stubs

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#28]
After running these three

```
meteor add angular2-compilers
meteor npm install --save angular2-meteor
meteor remove blaze-html-templates
```

**app.ts**

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2/bootstrap';

@Component({
  selector: 'app',
  templateUrl: 'client/app.html'
})
class Socially { }
bootstrap(Socially);
```

**app.html**

```
Hello World!
```

**index.html**

```
<body>
<app></app>
</body>
```

I got error in my terminal;

> Unable to resolve some modules:
>   "crypto" in /socially/node_modules/reflect-metadata/Reflect.js (web.browser)
> Consider running: meteor npm install --save meteor-node-stubs

However, the app can run well.
But if I run `meteor npm install --save meteor-node-stubs`, the error will be gone.

**Comment by dotansimha** [comment]
Closed in PR
