### ISSUE TITLE
Navigation in the tutorial seems to be broken

### ISSUE THREAD

**Issue by daudich** [Urigo/angular-meteor-docs#32]
Clicking on Next after the [Google Maps](http://www.angular-meteor.com/tutorials/socially/angular1/google-maps) step into [CSS-LESS-Bootstrap](http://www.angular-meteor.com/tutorials/socially/angular1/css-less-and-bootstrap) doesn't load the page but instead simply replaces the title. I noticed from the commit messages that the tutorial was updated. Perhaps related?

**Comment by Urigo** [comment]
yes that's because we haven't updated the tutorial from step 17 and beyond (just deployed a new version updated to Meteor 1.3 and modules).
I hope to finish this this weekend

**Comment by daudich** [comment]
Oh ok, but I think this might be a problem for those that are currently doing the tutorial. Perhaps revert and push everything at once?

**Comment by Urigo** [comment]
I think it's more important for people to get the updated version.
If by tomorrow we won't get everything sorted I will try to deploy the remaining chapters un-updated.
I think it's better that in the meantime you will go through the first chapters again, to get a better understanding of modules and components

**Comment by opensorceror** [comment]
I know you guys are updating the tutorial, but just wanted to let you know that none of the live demos hoster on meteor.com work either.

**Comment by Urigo** [comment]
steps 17 and 18 deployed now

**Comment by JohnBernardsson** [comment]
This gives me the chance to THANK YOU again @Urigo for all your huge and amazing work.

I am looking forward for the last sections of this tutorial, but I guess maybe Ionic 2 would be a problem? As they are not yet officially packing it for meteor... Do you have any thoughts about that?
