### ISSUE TITLE
4.22  Tests of PartyAdd doesn't work (Jasmine)

### ISSUE THREAD

**Issue by DonFabiolas** [Urigo/angular-meteor-docs#37]
from 4.22 and 4.23 on the tutorial, get some errors

after this : $ meteor npm run test:watch

here my console : 
=> Client modified -- refreshing
I20160410-15:51:00.388(2)? jasmine-client: 0 tests passed
W20160410-15:51:00.388(2)? (STDERR) jasmine-client: 3 tests failed
W20160410-15:51:00.388(2)? (STDERR) PartyAdd controller reset() should clean up party object
W20160410-15:51:00.388(2)? (STDERR) TypeError: window.module is not a function
W20160410-15:51:00.388(2)? (STDERR) app/app.js?hash=b90f029da37c802dc319259336ae5aee0bf6779d:28:12: TypeError: window.module is not a function
W20160410-15:51:00.388(2)? (STDERR) 
W20160410-15:51:00.388(2)? (STDERR) PartyAdd controller submit() should insert a new party
W20160410-15:51:00.388(2)? (STDERR) TypeError: window.module is not a function
W20160410-15:51:00.389(2)? (STDERR) app/app.js?hash=b90f029da37c802dc319259336ae5aee0bf6779d:28:12: TypeError: window.module is not a function
W20160410-15:51:00.389(2)? (STDERR) 
W20160410-15:51:00.389(2)? (STDERR) PartyAdd controller submit() should call reset()
W20160410-15:51:00.389(2)? (STDERR) TypeError: window.module is not a function
W20160410-15:51:00.389(2)? (STDERR) app/app.js?hash=b90f029da37c802dc319259336ae5aee0bf6779d:28:12: TypeError: window.module is not a function
W20160410-15:51:00.389(2)? (STDERR) 

Error comes from these : 

it('should clean up party object', () => {
        controller.party = party;
        controller.reset();

```
    expect(controller.party).toEqual({});
  });
```

...

it('should insert a new party', () => {
        expect(Parties.insert).toHaveBeenCalledWith(party);
      });

...

it('should call reset()', () => {
        expect(controller.reset).toHaveBeenCalled();
      });

Thank you

**Comment by kamilkisiela** [comment]
It's a sanjo:jasmine issue:
https://github.com/xolvio/meteor-jasmine/issues/332

**Comment by kamilkisiela** [comment]
@TroubadourFabiolas You can use [`1.0.1`](https://github.com/xolvio/meteor-jasmine/commit/8f03aa1522a29ac55a507dd0635be7743817dffd) version of sanjo:jasmine

**Comment by Urigo** [comment]
Deployed the fix with everything that @kamilkisiela has done.

Thanks @kamilkisiela !

**Comment by saulide** [comment]
I can  reproducible it with  sanjo:jasmine@1.0.1
