### ISSUE TITLE
Step 4 of Angular 2 Social App is broken

### ISSUE THREAD

**Issue by cferrier1995** [Urigo/angular-meteor-docs#4]
So from what I'm observing, the methods were used for the functionality to add a new party don't work anymore. 

I was unable to get it to work myself, hitting the 'add' button would do nothing and the 'addParty' function wouldn't even get hit. I then, just to confirm it wasn't on my end, Tried doing it with the exact contents of the provided Zip Files and had the same result. 

It appears that some change broke that method of calling the addParty function. I'd imagine if the livedemo was rebuilt the same result would be noticed.

**Comment by Urigo** [comment]
@cferrier1995 can you try it again with a clean install with the latest versions?
thanks

**Comment by cferrier1995** [comment]
Appears to be better now.

**Comment by Urigo** [comment]
Awesome.
Please re-open if it happens again
