### ISSUE TITLE
Socially section 3.9 has error

### ISSUE THREAD

**Issue by robertlight** [Urigo/angular-meteor-docs#41]
Towards the end of section 3, I was getting the following errors:

```
 Cannot find namespace 'Mongo' 
```

I had to do the following to get them to go away:

```
$ typings install meteor --ambient
```

**Comment by dotansimha** [comment]
We described it in step 0 (boostraping) under "TypeScript Typings" section - you need to install the Meteor imports, but the typings from `typings` is for Meteor 1.2 - the typings file for Meteor 1.3 is in the tutorial at the moment.
