### ISSUE TITLE
6.5  Handle success and fail for data actions doesn't work

### ISSUE THREAD

**Issue by DonFabiolas** [Urigo/angular-meteor-docs#48]
6.5  Handle success and fail for data actions doesn't work

this code after works but not your code in tutorial, miss something ?

Thank you

```
save() {
    Parties.update({
      _id: this.party._id
    }, {
      $set: {
        name: this.party.name,
        description: this.party.description
      }, errors() {
        if (error) {
          console.log('Oops, unable to update the party...');
        } else {
          console.log('Done!');
        }
      }
    }); //end of Parties.update({
  } //end of save() {
```

**Comment by Urigo** [comment]
is this Angular 2 or Angular 1?

**Comment by DonFabiolas** [comment]
Angular 1, here : http://www.angular-meteor.com/tutorials/socially/angular1/bind-one-object

here, you are, the copy/paste from the tutorial : 

This doesn't work for me

6.5  Handle success and fail for data actions imports/ui/components/partyDetails/partyDetails.js »

```
    name: this.party.name,
    description: this.party.description
  }
}, (error) =&gt; {
  if (error) {
    console.log('Oops, unable to update the party...');
  } else {
    console.log('Done!');
  }
});
```

  }
}

**Comment by DonFabiolas** [comment]
I've just seen this : 
In google chrome browser
here : http://www.angular-meteor.com/tutorials/socially/angular1/bind-one-object
It displays : `}, (error) =&gt; {`

here : https://github.com/Urigo/meteor-angular-socially/commit/826b42bc5f91bd0c33643daa442b87e320c23169
It displays : `}, (error) => {`

but I've already errors :  
{ [SyntaxError: /imports/ui/components/partyDetails/partyDetails.js: Unexpected token (35:9)]
  pos: 769,
  loc: { line: 35, column: 9 },
  _babel: true,
  codeFrame: '\u001b[0m        name\u001b[1m:\u001b[22m \u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mparty\u001b[1m.\u001b[22mname\u001b[1m,\u001b[22m\n        description\u001b[1m:\u001b[22m \u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mparty\u001b[1m.\u001b[22mdescription\n      \u001b[32m}\u001b[39m\u001b[1m,\u001b[22m \u001b[34m\u001b[1m(\u001b[22m\u001b[39merror\u001b[34m\u001b[1m)\u001b[22m\u001b[39m \u001b[1m=>\u001b[22m \u001b[32m{\u001b[39m\n        \u001b[36mif\u001b[39m \u001b[34m\u001b[1m(\u001b[22m\u001b[39merror\u001b[34m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\n          console\u001b[1m.\u001b[22mlog\u001b[34m\u001b[1m(\u001b[22m\u001b[39m\u001b[31m\'Oops, unable to update the party...\'\u001b[39m\u001b[34m\u001b[1m)\u001b[22m\u001b[39m\u001b[1m;\u001b[22m\n        \u001b[32m}\u001b[39m \u001b[36melse\u001b[39m \u001b[32m{\u001b[39m\u001b[0m' }
{ [SyntaxError: /imports/ui/components/partyDetails/partyDetails.js: Unexpected token (35:9)]
  pos: 769,
  loc: { line: 35, column: 9 },
  _babel: true,
  codeFrame: '\u001b[0m        name\u001b[1m:\u001b[22m \u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mparty\u001b[1m.\u001b[22mname\u001b[1m,\u001b[22m\n        description\u001b[1m:\u001b[22m \u001b[36mthis\u001b[39m\u001b[1m.\u001b[22mparty\u001b[1m.\u001b[22mdescription\n      \u001b[32m}\u001b[39m\u001b[1m,\u001b[22m \u001b[34m\u001b[1m(\u001b[22m\u001b[39merror\u001b[34m\u001b[1m)\u001b[22m\u001b[39m \u001b[1m=>\u001b[22m \u001b[32m{\u001b[39m\n        \u001b[36mif\u001b[39m \u001b[34m\u001b[1m(\u001b[22m\u001b[39merror\u001b[34m\u001b[1m)\u001b[22m\u001b[39m \u001b[32m{\u001b[39m\n          console\u001b[1m.\u001b[22mlog\u001b[34m\u001b[1m(\u001b[22m\u001b[39m\u001b[31m\'Oops, unable to update the party...\'\u001b[39m\u001b[34m\u001b[1m)\u001b[22m\u001b[39m\u001b[1m;\u001b[22m\n        \u001b[32m}\u001b[39m \u001b[36melse\u001b[39m \u001b[32m{\u001b[39m\u001b[0m' }
=> Errors prevented startup:                  

   While building for web.browser:
   imports/ui/components/partyDetails/partyDetails.js:35:9: Unexpected token
   (35:9)

   While processing files with pbastowski:angular-babel (for target
   web.browser):
   imports/ui/components/partyDetails/partyDetails.js:35:9: Babel transform
   error

   While processing files with pbastowski:angular-babel (for target
   os.osx.x86_64):
   imports/ui/components/partyDetails/partyDetails.js:35:9: Babel transform
   error

**Comment by Urigo** [comment]
deployed the fix of @kamilkisiela
