### ISSUE TITLE
duplicated `location: string;` in Step 16.1

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#52]
In [16.1  Extend party location with lat and lng coordinates](http://www.angular-meteor.com/tutorials/socially/angular2/google-maps), right now is:

```
  name: string;
  description?: string;
  location: string;
  location: {
    name: string;
    lat?: number;
    lng?: number;
  };
  invited?: Array<string>;
  rsvps?: Array<RSVP>;
}
```

need remove duplicated `location: string;`

**Comment by Urigo** [comment]
fixed in the new tutorial
