### ISSUE TITLE
live demos broken

### ISSUE THREAD

**Issue by opensorceror** [Urigo/angular-meteor-docs#56]
I know you guys are updating the tutorial, but just wanted to let you know that none of the live demos hosted on meteor.com work either.

**Comment by kamilkisiela** [comment]
@opensorceror [The reason](https://forums.meteor.com/t/meteor-com-free-hosting-ends-march-25-2016/19308) - ( [ with soundtrack :mute: ](https://www.youtube.com/watch?v=fV4DiAyExN0) )

**Comment by Urigo** [comment]
:)
I hope to get them back on Galaxy soon

**Comment by Urigo** [comment]
look at this [comment](https://github.com/Urigo/angular-meteor-docs/pull/81#issuecomment-237843386)
