### ISSUE TITLE
Ambiguity between Meteor.isClient and using the client folder

### ISSUE THREAD

**Issue by riscie** [Urigo/angular-meteor-docs#64]
Within the Angular1 tutorials, Step 0 - Bootstrapping, the tutorial explains us how Meteor.isClient is used:
`There are a few ways to tell Meteor to run code only on the client/server/mobile side, let's start with the simplest way - Meteor.isClient variable.`

But then we do not need it in the main.js file we create. (Supposably because we put the main.js file within the client folder of our structure, where it will not be executed on the server anyway). 

Also a bit earlier in the text, the instruction is to create main.js in the project-root. But in 0.9 the file is, as mentioned above, placed within the client folder.

I think this ambiguity happened after updating the tutorial to meteor 1.3. Am I right?

I would update the doc, but english is not my native language and I don't think I would get it right the first time because I am very new to meteor.

Cheers Matthias

**Comment by kamilkisiela** [comment]
@riscie  #73 should fix it
