### ISSUE TITLE
import MeteorComponent way should be updated

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#70]
After updating angular2-meteor from 0.5.2 to 0.5.3
`import { MeteorComponent } from 'angular2-meteor/meteor_component';`
needs change to
`import { MeteorComponent } from 'angular2-meteor';`

Refer to [here](https://github.com/Urigo/angular2-meteor/issues/237)

**Comment by Urigo** [comment]
updated in the new version of the tutorial
