### ISSUE TITLE
Can't follow tutorial, breaks at Step 3

### ISSUE THREAD

**Issue by radonthetyrant** [Urigo/angular-meteor-docs#76]
Site: http://www.angular-meteor.com/tutorials/socially/angular2/3-way-data-binding
In the Section "Blaze-like Binding to Angular", Code block 3.7

The Program breaks, because of

```
parties: Mongo.Cursor<Object>;
```

Meteor won't start the Server after this with error message

```
Cannot find namespace 'Mongo'.
```

https://gist.github.com/radonthetyrant/a1ebec141a9f4e93f7d708e73429ba90.js

**Comment by kamilkisiela** [comment]
Try to:

``` ts
import { Mongo } from 'meteor/mongo';
```

**Comment by Urigo** [comment]
fixed in the new version of the tutorial
