### ISSUE TITLE
A more detailed section for the folder structure

### ISSUE THREAD

**Issue by hongbo-miao** [Urigo/angular-meteor-docs#78]
As barbatus suggests, move [original post](https://github.com/Urigo/angular2-meteor/issues/148) to here.

---

Right now the [Step 7 - Folder structure](http://www.angular-meteor.com/tutorials/socially/angular2/folder-structure) for actual file structure does not describe too much, only says "server" and "client" from meteor side in general.

But if the project it big, what would the folder structure look like from angular2-meteor side?

**For client part:**

```
client/
----- styles/
---------- main.css
----- lib/
---------- calendar.pipe.ts
---------- truncate.pipe.ts
----- services/
---------- alert.service.ts
----- components/
---------- home/
--------------- home.component.ts
--------------- home.component.html
--------------- home.component.css
--------------- home.service.ts
---------- about/
--------------- about.component.ts
--------------- about.component.html
--------------- about.component.css
--------------- about.service.ts
----- app.ts
```

or 

```
client/
----- styles/
---------- main.css
----- lib/
---------- calendar.pipe.ts
---------- truncate.pipe.ts
----- services/
---------- alert.service.ts
----- home/
---------- components/
--------------- home.component.ts
--------------- home.component.html
--------------- home.component.css
--------------- home.service.ts
----- about/
---------- components/
--------------- about.component.ts
--------------- about.component.html
--------------- about.component.css
--------------- about.service.ts
----- app.ts
```

or something else.
Also, right now socially does not have services, if it has, where it should be.

**For other parts:**

```
server/
----- main.ts
collections/
----- methods.ts
public/
----- img/
```

Some sources:
https://github.com/mgechev/angular2-seed
https://scotch.io/tutorials/angularjs-best-practices-directory-structure
http://meteortips.com/first-meteor-tutorial/structure/

**Comment by Urigo** [comment]
@Hongbo-Miao would you be willing to PR chapter 7 to make it better?

**Comment by Hongbo-Miao** [comment]
@Urigo Sure, I will do it later, but then I think I want to changed all files name too based on Angular 2 official style, like **home.component.ts**

**Comment by hongbo-miao** [comment]
@Urigo Sure, I will do it later once I think I am ready, I will write some suggestions based on both Angular 2 and Meteor official styles. Kind of combining them.

**Comment by Urigo** [comment]
very nice, looking forward to this
