### ISSUE TITLE
Module error in step 3

### ISSUE THREAD

**Issue by amitton** [Urigo/angular-meteor-docs#80]
Upon running meteor in step 3 I get the following errors:
Cannot find module 'meteor/mongo'
Cannot find name 'NgZone'

**Comment by hongbo-miao** [comment]
Hi @amitton I explained a little bit in [Meteor forum](https://forums.meteor.com/t/for-people-who-are-following-socially-tutorial-and-met-problems/22994). See whether it helps.

**Comment by Urigo** [comment]
I've updated the tutorial to fix that.
thanks for the help!
