### ISSUE TITLE
Step 22 Ionic zip file is not the good one

### ISSUE THREAD

**Issue by DonFabiolas** [Urigo/angular-meteor-docs#88]
Hello,

At the beginning of the tutorial, we should download a zip file related of the step 22 tutorial.
The problem is the zip corresponds to the step 21.
here : 

> Note: If you skipped ahead to this section, here is a zip of the tutorial at this point.

**Please, could you update the good zip file for the step 22 ?**

Thank you

**Comment by kamilkisiela** [comment]
It should be fixed now :) if not, we should wait for @Urigo to publish the new version that has been recently merged.

**Comment by Urigo** [comment]
published.
closing, please open a new issue if the problem still happens
