### ISSUE TITLE
import problems after bootstrab step 0

### ISSUE THREAD

**Issue by spike83** [Urigo/angular-meteor-docs#89]
At the end of 0 bootstraping  step in socially Angular2 tutorial i got errors like:

```
=> Started MongoDB.
client/app.ts (3, 25): Cannot find module 'angular2/core'.
client/app.ts (4, 25): Cannot find module 'angular2/platform/browser'.
```

In webstorm ide i got hints, that the imports will not work because the folders an files were missing.

```
import {Component} from 'angular2/core';
import {bootstrap} from 'angular2/platform/browser';
```

I saw, that in package.json was a diffrence between mine and the repos here.

mine:

```
  "dependencies": {
    "@angular/core": "^2.0.0-rc.1",
...
```

repos:

```
"dependencies": {
"angular2": "2.0.0-rc.1",
```

https://github.com/Urigo/meteor-angular2.0-socially/blob/master/package.json#L7

I solved this by installing @angular/platform-browser-dynamic with the following command (according angular2 quickstart tutorial):

```
meteor npm install @angular/platform-browser-dynamic --save
```

afterwartds I had to update the imports with:

```
import {Component} from '@angular/core';
import {bootstrap} from '@angular/platform-browser-dynamic';
```

What is the reason for the diffrence?

Best Regards
Simon

**Comment by hongbo-miao** [comment]
Hi @spike83 I explained a little bit in [Meteor forum](https://forums.meteor.com/t/for-people-who-are-following-socially-tutorial-and-met-problems/22994).

**Comment by spike83** [comment]
Thanks for explanation. I'm looking forward to see this stuff become stable. It rocks!
If I get it work I'll provide a pull request.

**Comment by Urigo** [comment]
I've updated the tutorial.
thanks for the help!
