### ISSUE TITLE
angular-meteor.com: error in the console

### ISSUE THREAD

**Issue by barbatus** [Urigo/angular-meteor-docs#90]
Error in the console on every load: `Router.current(...).data` is not function at `Object.Template.layout.helpers.currentApi`

**Comment by Urigo** [comment]
@praneybehl is the site still not working for you or it's just the console.log error?

**Comment by praneybehl** [comment]
@Urigo thanks mate, its fixed, what when wrong?

**Comment by Urigo** [comment]
some outdated versions of `iron:router`...
we really need to change the site to use Angular 2.0 instead of Blaze :)
